blank_issues_enabled: false
contact_links:
  - name: 📖 Wiki
    url: https://github.com/nulldg/DiscordChatExporter/wiki
    about: Find usage guides and frequently asked questions.
  - name: 🗨 Discussions
    url: https://github.com/nulldg/DiscordChatExporter/discussions/new
    about: Ask and answer questions.