name: auto-deploy

on: push

jobs:
  deploy:
    if: ${{ github.ref_type == 'tag' }}
    runs-on: windows-latest

    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Install .NET
        uses: actions/setup-dotnet@4.0.0
        with:
          dotnet-version: 8.0.x

      - name: Publish (CLI)
        run: >
            dotnet publish DiscordChatExporter.Cli/
            -p:Version=${{ github.ref_type == 'tag' && github.ref_name || '0.0.0' }}
            --output DiscordChatExporter.Cli/bin/Publish/
            --configuration Release

      - name: Publish (GUI)
        run: >
            dotnet publish DiscordChatExporter.Gui/
            -p:Version=${{ github.ref_type == 'tag' && github.ref_name || '0.0.0' }}
            -o DiscordChatExporter.Gui/bin/Publish/
            --configuration Release

      - name: Create package (CLI)
        run: Compress-Archive -Path DiscordChatExporter.Cli/bin/Publish/* -DestinationPath DiscordChatExporterPlus.Cli.zip -Force
        shell: pwsh

      - name: Create package (GUI)
        run: Compress-Archive -Path DiscordChatExporter.Gui/bin/Publish/* -DestinationPath DiscordChatExporterPlus.zip -Force
        shell: pwsh

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            DiscordChatExporterPlus.Cli.zip
            DiscordChatExporterPlus.zip
