name: main

on: push

jobs:
  deploy:
    if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
    runs-on: windows-latest

    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Publish (CLI)
        run: dotnet publish DiscordChatExporter.Cli/ -o DiscordChatExporter.Cli/bin/Publish/ --configuration Release

      - name: Publish (GUI)
        run: dotnet publish DiscordChatExporter.Gui/ -o DiscordChatExporter.Gui/bin/Publish/ --configuration Release

      - name: Create package (CLI)
        run: Compress-Archive -Path DiscordChatExporter.Cli/* -DestinationPath DiscordChatExporterPlus.Cli.zip -Force
        shell: pwsh

      - name: Create package (GUI)
        run: Compress-Archive -Path DiscordChatExporter.Gui/* -DestinationPath DiscordChatExporterPlus.zip -Force
        shell: pwsh

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            DiscordChatExporterPlus.Cli.zip
            DiscordChatExporterPlus.zip
          body: |
            [Changelog](https://github.com/nulldg/DiscordChatExporter/blob/master/Changelog.md)